### ISSUE TITLE
Error Running dgfr::similarity cluster

### ISSUE THREAD

**Issue by kfh88** [lailaviana/dgfr#1]
When running dgfr::similarity cluster I received the following error and traceback. It appears that there is a requirement for the column names to start with t in the score file for this part of the code to work. I could be mistaken about this but when I edited by initial data so that all the gene ids started with "transcript_" the code ran correctly. 

16.
stop(fallback)
15.
signal_abort(cnd, .file)
14.
rlang::abort(message, ..., call = call, use_cli_format = TRUE,
.frame = .frame)
13.
cli::cli_abort("{.arg cols} must select at least one column.",
call = error_call)
12.
build_longer_spec(data = data, cols = {
{
cols
} ...
11.
pivot_longer.data.frame(tibble::rownames_to_column(score_file,
var = "gene1"), cols = starts_with("T"), names_to = "gene2",
values_to = "similarity")
10.
tidyr::pivot_longer(tibble::rownames_to_column(score_file, var = "gene1"),
cols = starts_with("T"), names_to = "gene2", values_to = "similarity")
9.
dplyr::left_join(tidyr::pivot_longer(tibble::rownames_to_column(score_file,
var = "gene1"), cols = starts_with("T"), names_to = "gene2",
values_to = "similarity"), kmeans_output, by = dplyr::join_by(gene1 ==
name))
8.
dplyr::rename(dplyr::left_join(tidyr::pivot_longer(tibble::rownames_to_column(score_file,
var = "gene1"), cols = starts_with("T"), names_to = "gene2",
values_to = "similarity"), kmeans_output, by = dplyr::join_by(gene1 ==
name)), cluster_gene1 = cluster)
7.
dplyr::select(dplyr::rename(dplyr::left_join(tidyr::pivot_longer(tibble::rownames_to_column(score_file,
var = "gene1"), cols = starts_with("T"), names_to = "gene2",
values_to = "similarity"), kmeans_output, by = dplyr::join_by(gene1 ==
name)), cluster_gene1 = cluster), gene1, gene2, similarity, ...
6.
dplyr::left_join(dplyr::select(dplyr::rename(dplyr::left_join(tidyr::pivot_longer(tibble::rownames_to_column(score_file,
var = "gene1"), cols = starts_with("T"), names_to = "gene2",
values_to = "similarity"), kmeans_output, by = dplyr::join_by(gene1 ==
name)), cluster_gene1 = cluster), gene1, gene2, similarity, ...
5.
dplyr::rename(dplyr::left_join(dplyr::select(dplyr::rename(dplyr::left_join(tidyr::pivot_longer(tibble::rownames_to_column(score_file,
var = "gene1"), cols = starts_with("T"), names_to = "gene2",
values_to = "similarity"), kmeans_output, by = dplyr::join_by(gene1 ==
name)), cluster_gene1 = cluster), gene1, gene2, similarity, ...
4.
dplyr::select(dplyr::rename(dplyr::left_join(dplyr::select(dplyr::rename(dplyr::left_join(tidyr::pivot_longer(tibble::rownames_to_column(score_file,
var = "gene1"), cols = starts_with("T"), names_to = "gene2",
values_to = "similarity"), kmeans_output, by = dplyr::join_by(gene1 ==
name)), cluster_gene1 = cluster), gene1, gene2, similarity, ...
3.
dplyr::mutate(dplyr::select(dplyr::rename(dplyr::left_join(dplyr::select(dplyr::rename(dplyr::left_join(tidyr::pivot_longer(tibble::rownames_to_column(score_file,
var = "gene1"), cols = starts_with("T"), names_to = "gene2",
values_to = "similarity"), kmeans_output, by = dplyr::join_by(gene1 ==
name)), cluster_gene1 = cluster), gene1, gene2, similarity, ...
2.
dplyr::filter(dplyr::mutate(dplyr::select(dplyr::rename(dplyr::left_join(dplyr::select(dplyr::rename(dplyr::left_join(tidyr::pivot_longer(tibble::rownames_to_column(score_file,
var = "gene1"), cols = starts_with("T"), names_to = "gene2",
values_to = "similarity"), kmeans_output, by = dplyr::join_by(gene1 ==
name)), cluster_gene1 = cluster), gene1, gene2, similarity, ...
1.
dgfr::similarity_cluster(score_file = score_file, kmeans_output = kmeans_output,
output_type = "table")

**Comment by lailaviana** [comment]
Hi, thanks for opening the issue.

You were right; the column names needed to start with 't'. I have corrected it, and it should run smoothly now.
